### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by OlofT** [SwiftJava/swift-android-kotlin#3]
After downloading and running the first command, it fails. Downloading from the browser works.

$ swift-install/setup.sh
Downloading http://services.gradle.org/distributions/gradle-4.1-all.zip

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-4.1-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-4.1-all.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1985)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1577)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.wrapper.Install$1.call(Install.java:60)
	at org.gradle.wrapper.Install$1.call(Install.java:47)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	... 3 more

---
This project looks really interesting and I would like to try it out!

**Comment by johnno1962** [comment]
Hi, What version of android toolchain are you using? Is this where the setup.sh comes from?

**Comment by OlofT** [comment]
I'm using your supplied version, http://johnholdsworth.com/android_toolchain.tgz
And yes, that's where setup.sh comes from

**Comment by johnno1962** [comment]
Looks like that version of gradle has been deprecated. My release is some 5 years old now. You should fare better with the "Readdle" Swift toolchains which are more up to date: https://github.com/readdle/swift-android-toolchain

**Comment by OlofT** [comment]
Yes, 5 years is a bit too old I guess - but their tools have other problems and are also not working. I have the toolchain compiled for Android and now I'm looking for a clean way to wrap it all together. It seems this should be doable, and people like you have done it, but there are a bit too many "moving parts". Also not familiar with the Gradle build system. 

Could you point me in the right direction?

**Comment by johnno1962** [comment]
If their toolchain has problems, you should raise an issue with them as I'm sure they'd like to know. @zayass, can you help out here?

**Comment by OlofT** [comment]
Already have! I'm probing all alternatives! =)
